### ISSUE TITLE
There's no Android version of this? 

### ISSUE THREAD

**Issue by Shirou27** [Zintom/GameOptimizer#22]
I want to try it but it's only available in PC. i don't have PC so can you make Android version of this?

**Comment by Zintom** [comment]
I appreciate the interest. Unfortunately, Android operates in a completely different realm when it comes to optimizations. An Android application can only control its own Thread priorities etc, not any other applications.

So to answer your question, no, an Android version cannot/will-not be created. The functionality of this program isn't remotely compatible with any Android specific optimizations.

Any Android app would be vastly different to the one created for PC and so would want it's own project. If that sounds like your cup of tea, then by all means build your own optimizer for Android. Unfortunately I don't have the knowledge surrounding Android[third party optimizations] nor the time to build such a project myself.

Cheers,
Tom
